use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::PathBuf,
    time::SystemTime,
};

use crate::utils::{format_bytes, format_duration, current_timestamp};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FuzzingReport {
    pub session_id: String,
    pub start_time: u64,
    pub end_time: u64,
    pub duration_seconds: f64,
    pub protocol: String,
    pub target: String,
    pub total_executions: u64,
    pub crashes_found: usize,
    pub interesting_cases: usize,
    pub coverage_percentage: f64,
    pub exec_per_second: f64,
    pub summary: String,
}

pub struct ReportGenerator;

impl ReportGenerator {
    pub fn new() -> Self {
        Self
    }
    
    pub fn generate_html_report(&self, report: &FuzzingReport, output_path: &PathBuf) -> Result<()> {
        let html_content = self.create_html_content(report);
        fs::write(output_path, html_content)?;
        Ok(())
    }
    
    pub fn generate_markdown_report(&self, report: &FuzzingReport, output_path: &PathBuf) -> Result<()> {
        let markdown_content = self.create_markdown_content(report);
        fs::write(output_path, markdown_content)?;
        Ok(())
    }
    
    fn create_html_content(&self, report: &FuzzingReport) -> String {
        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Network Protocol Fuzzer Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        .metric {{ display: inline-block; margin: 10px 20px 10px 0; padding: 15px; background-color: #ecf0f1; border-radius: 5px; min-width: 150px; }}
        .metric-value {{ font-size: 24px; font-weight: bold; color: #2980b9; }}
        .metric-label {{ font-size: 14px; color: #7f8c8d; margin-top: 5px; }}
        .success {{ color: #27ae60; }}
        .warning {{ color: #f39c12; }}
        .danger {{ color: #e74c3c; }}
        .summary {{ background-color: #f8f9fa; padding: 20px; border-left: 4px solid #3498db; margin: 20px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #3498db; color: white; }}
        .footer {{ margin-top: 40px; text-align: center; color: #7f8c8d; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 Network Protocol Fuzzer Report</h1>
        
        <div class="summary">
            <h3>Executive Summary</h3>
            <p>{}</p>
        </div>
        
        <h2>📊 Key Metrics</h2>
        <div class="metric">
            <div class="metric-value">{}</div>
            <div class="metric-label">Total Executions</div>
        </div>
        <div class="metric">
            <div class="metric-value {}">{}</div>
            <div class="metric-label">Crashes Found</div>
        </div>
        <div class="metric">
            <div class="metric-value">{:.2}%</div>
            <div class="metric-label">Coverage</div>
        </div>
        <div class="metric">
            <div class="metric-value">{:.1}</div>
            <div class="metric-label">Exec/sec</div>
        </div>
        <div class="metric">
            <div class="metric-value">{}</div>
            <div class="metric-label">Duration</div>
        </div>
        
        <h2>🎯 Target Information</h2>
        <table>
            <tr><th>Protocol</th><td>{}</td></tr>
            <tr><th>Target</th><td>{}</td></tr>
            <tr><th>Session ID</th><td>{}</td></tr>
            <tr><th>Start Time</th><td>{}</td></tr>
            <tr><th>End Time</th><td>{}</td></tr>
        </table>
        
        <div class="footer">
            Generated by Network Protocol Fuzzer v0.1.0
        </div>
    </div>
</body>
</html>"#,
            report.summary,
            report.total_executions,
            if report.crashes_found > 0 { "danger" } else { "success" },
            report.crashes_found,
            report.coverage_percentage,
            report.exec_per_second,
            format_duration(report.duration_seconds),
            report.protocol,
            report.target,
            report.session_id,
            self.format_timestamp(report.start_time),
            self.format_timestamp(report.end_time),
        )
    }
    
    fn create_markdown_content(&self, report: &FuzzingReport) -> String {
        format!(
            r#"# 🔍 Network Protocol Fuzzer Report

## Executive Summary

{}

## 📊 Key Metrics

| Metric | Value |
|--------|-------|
| Total Executions | {} |
| Crashes Found | {} |
| Coverage | {:.2}% |
| Exec/sec | {:.1} |
| Duration | {} |

## 🎯 Target Information

| Property | Value |
|----------|-------|
| Protocol | {} |
| Target | {} |
| Session ID | {} |
| Start Time | {} |
| End Time | {} |

## 📈 Performance

- **Execution Rate**: {:.1} executions per second
- **Total Runtime**: {}
- **Coverage Achieved**: {:.2}%

## 🐛 Security Findings

{} crashes were discovered during the fuzzing session.

---

*Generated by Network Protocol Fuzzer v0.1.0*
"#,
            report.summary,
            report.total_executions,
            report.crashes_found,
            report.coverage_percentage,
            report.exec_per_second,
            format_duration(report.duration_seconds),
            report.protocol,
            report.target,
            report.session_id,
            self.format_timestamp(report.start_time),
            self.format_timestamp(report.end_time),
            report.exec_per_second,
            format_duration(report.duration_seconds),
            report.coverage_percentage,
            report.crashes_found,
        )
    }
    
    fn format_timestamp(&self, timestamp: u64) -> String {
        use std::time::{UNIX_EPOCH, Duration};
        
        if let Some(datetime) = SystemTime::UNIX_EPOCH.checked_add(Duration::from_secs(timestamp)) {
            format!("{:?}", datetime) // Simple formatting, could use chrono for better formatting
        } else {
            format!("Invalid timestamp: {}", timestamp)
        }
    }
}

impl Default for ReportGenerator {
    fn default() -> Self {
        Self::new()
    }
}